config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:index, :create, :update]
  get '/room/join/:id/' => 'rooms#join'
  post '/room/leave/:id/' => 'rooms#leave'
  get '/room/share/:id/' => 'rooms#share'
  get '/room/edit/:id/' => 'rooms#edit'
  get '/join/:id' => 'rooms#directjoin'
  get '/embed/:id' => 'main#embed'

  get '/message/receive/:id' => 'chats#receive'
  post '/message/send' => 'chats#sendmsg'
  post '/room/ban' => 'rooms#ban', as: 'room_user_ban'

  patch '/user/set-name' => 'users#set_name', as: 'user_name_set'
  patch '/user/set-pass' => 'users#set_password', as: 'user_password_set'
  patch '/user/set-profile' => 'users#set_profile', as: 'user_profile_set'

  patch '/room/' => 'rooms#update'

  post '/user/hello' => 'users#hello'
  post '/user/goodbye' => 'users#goodbye'
  get '/user/:id' => 'users#show'
  delete '/user/wipe/:id' => 'users#wipe', as: 'wipe_user'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  resources :users
  root 'main#chat'

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def chat
    @joined = current_user.tenancies.where(active: true).includes(:room)
    @popular_rooms = Room.all.order("popularity DESC").limit(12)
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_alerts.html.erb
<% if !current_user.username_set %>
  <div class="alert-push"></div>

  <div class="alert-card" id="pass-set">
    <h3> <%= t('namealert') %> </h3>
    <p> <%= t('namealertcall') %> </p>

    <%= form_for current_user, url: user_name_set_path, method: :patch, remote: true do |f| %>
      <%= f.text_field :username, minlength: "2", maxlength: "15", placeholder: t('profilename'), class: "form-input", value: nil ,rows: 1, required: true %>
    <% end %>
  </div>

<% elsif current_user.password_digest.nil? %>
  <div class="alert-push"></div>

  <div class="alert-card" id="pass-set">
    <h3> <%= t('passalert') %> </h3>
    <p><%= t('passalertcall') %> </p>

    <%= form_for current_user, url: user_password_set_path, method: :patch, remote: true do |f| %>
      <%= f.password_field :password, minlength: "4", maxlength: "80", placeholder: t('yourpass'), class: "form-input" ,rows: 1, required: true %>
    <% end %>
  </div>

<% elsif current_user.photo.url.nil? %>
  <div class="alert-push"></div>

  <div class="alert-card profile-edit" style="cursor:pointer">
    <h3><%= t('photoalert') %> </h3>
    <p><%= t('photoalertcall') %> </p>
  </div>

<% else %>
  <div class="alert-push enable-notifications hidden"></div>

  <div class="alert-card enable-notifications hidden" style="cursor:pointer">
    <h3><%= t('notificationalert') %> </h3>
    <p><%= t('notificationcall1') %> </p>
    <p><%= t('notificationcall2') %> </p>
  </div>
<% end %>

app/views/main/chat.html.erb
<div class="top-bar">
  <%#= image_tag "lero5.png", class: "logo" %>
  <%#= image_tag "home.png", class: "logo " %>
  <!-- Build a notifications counter -->

  <div class="top-side">
  <%= image_tag "lero.png", class: "logo explore" %>
    <div class="profile-card profile-edit">
      <% if current_user.photo.blank? %>
      <%= image_tag "user-default.png" %>
      <% else %>
      <%= image_tag current_user.photo.url.to_s %>
      <% end %>

      <% if current_user.username_set %>
        <%= current_user.name %>
      <% else %>
        <%= t("guest") %>
      <% end %>
    </div>
  </div>
</div>

<div class="containerd">
  <aside class="control row-bs <%= 'hidden-mobile' if !@joined.any? %>">
    <div class="side-head">
      <div class="side-back hidden">
        <%= image_tag("side-back.png", class: "side-back", title: "Back") %>
      </div>

      <h2 class="side-title"> <%= t('rooms') %> </h2>

      <div class="side-actions">
        <% if current_user.username_set %>
          <%= image_tag("profile-edit.png", class: "profile-edit hidden-desktop", title: "Edit Profile") %>
          <%= image_tag("room-new.png", class: "room-new", title: "New room") %>
        <% else %>
        <div class="login-button"> <%= t('login') %> </div>
        <% end %>
      </div>
    </div>

    <div class="window window-main" data-name="<%= t('rooms') %>">

      <ul class="room-tabs">
        <% if @joined.any? %>
          <% @joined.each do |t| %>
            <li class="room-tab" data-id="<%= t.room.id %>" data-moderator="<%= t.moderator %>"> <%= t.room.name %> <span>  </span> </li>
          <% end %>
        <% end %>
      </ul>
      <span class="explore"> <%= image_tag "room-share.png" %> <%= t('morerooms') %> </span>

      <%= render 'main/alerts' %>

    </div>

    <div class="window window-room-new hidden" data-name="Nova sala">
      <div class="room-error"></div>
      <%= form_for Room.new, remote: true do |f| %>

        <%= image_tag "lero6.png" %>
        <%= f.file_field :photo, accept: "image/png, image/gif, image/jpeg" %>
        <%= f.text_field :name, minlength: "2", maxlength: "15", placeholder: t('roomname'), class: "form-input", required: true %>
        <%= f.text_area :description, minlength: "2", maxlength: "40", placeholder: t('roomdescription'), class: "form-textarea-sm", rows: 3 %>
        <%= f.submit t('formsubmit'), class: "form-submit" %>
      <% end %>
    </div>

    <div class="window window-profile-edit hidden" data-name="<%= current_user.username_set ? "@#{current_user.username}" : t('profileedit') %>">
      <div class="profile-error"></div>
      <%= form_for current_user,url: user_profile_set_path, method: :patch, remote: true do |f| %>

        <div class="form-photo">
          <% if current_user.photo? %>
          <%= image_tag current_user.photo.url.to_s %>
          <% else %>
          <%= image_tag "user-default.png" %>
          <% end %>

          <%= f.file_field :photo, accept: "image/png, image/gif, image/jpeg" %>
        </div>
        <% if !current_user.username_set %>
        <%= f.text_field :username, minlength: "2", maxlength: "15", placeholder: t('profilename'), class: "form-input", value: "", required: true %>
        <% else %>
        <%= f.text_field :name, minlength: "2", maxlength: "15", placeholder: t('profilename'), class: "form-input", required: true %>
        <% end %>
        <%= f.text_area :bio, minlength: "2", maxlength: "50", placeholder: t('profilebio'), class: "form-textarea-sm", rows: 3 %>
        <%= f.submit t('save'), class: "form-submit" %>
      <% end %>
    </div>

    <div class="window window-ajax-content hidden" data-name="<%= t('loading') %>">

    </div>

  </aside>

  <div class="chat row-bs <%= 'hidden-mobile' if @joined.any? %>">
    <div class="chat-head">
      <div class="room-back hidden-desktop">
        <%= image_tag("side-back.png", class: "room-back") %>
      </div>
      <h2 class="chat-title"> <%= t('popular') %>  </h2>
      <div class="room-actions hidden">
        <%= image_tag("room-edit.png", class: "room-edit mod-actions hidden", title: "Edit room") %>
        <%= image_tag("room-ban.png", class: "room-ban mod-actions hidden", title: "Ban a user") %>
        <%#= image_tag("room-share.png", class: "room-hotlink", title: "Share join link") %>
        <%= image_tag("room-leave.png", class: "room-leave", title: "Leave room") %>
      </div>

    <div id="chat-container" class="full-height">

      <% @joined.each do |t| %>
        <div class="room" data-id="<%= t.room.id %>"> </div>
      <% end %>

      <div class="landing">

        <%= image_tag "lero.png" %>

        <div class="landing-intro">
          <h1> <%= t('lero') %> </h1>
          <p> <%= t('aboutlero') %> </p>
        </div>

        <h3 class="hidden-mobile"> <%= t('popularnow') %> </h3>


        <div class="room-popular clearfix">
          <% @popular_rooms.each do |r| %>
            <div class="room-card" data-id="<%= r.id %>">
              <%= image_tag r.photo? ? r.photo.url.to_s : "lero5.png"  %>
              <div class="room-card-description">
                <h6> <%= r.name %> </h6>
                <p> <%= r.description %> </p>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <!--  youtoba --
          <div class="videoWrapper">
              <%#= raw(youtube_embed(p.linkcontent)) %>
          </div>
      <!-- site --
          <%#= link_to p.linkcontent, :rel => 'nofollow', :target => "_blank" do %>
          <div class="card2 opgobject" data-cat="<%#= p.category %>">
              <%# if !p.opgimageurl.nil? %>
                <div class="opgimage" style="background-image:url(<%#= image_path(p.opgimageurl, alt: p.opgtitle) %>);">

                </div>
              <%# end %>
              <div class="opg-info">
                <h3 class="opgtitle"> <%#= p.opgtitle %> </h2>
                <div class="opgdescription">
                  <span class="opgtext"> <%#= p.opgdescription if !p.opgdescription.nil? %> </span>
                </div>
              </div>
          </div>
-->


    </div>

    <div class="chat-insert">
      <% if current_user.username_set %>
        <textarea placeholder="<%= t('messagebox') %>" id="compose" rows="1" data-room-id="1" class="hidden"></textarea>
        <input id="link" class="hidden"></input>
      <% else %>
        <div class="form-username hidden">
          <div id="error-div"> </div>
          <div class="form-new-user">
            <%= form_for current_user, url: user_name_set_path, method: :patch, remote: true do |f| %>
            <h3 class="hidden-mobile"> <%= t('introname') %> </h3>
              <%= f.text_field :username, minlength: "2", maxlength: "15", placeholder: t('profilename'),value: nil ,rows: 1, required: true %>
            <% end %>
          </div>

          <div class="form-login hidden">
            <%= form_for(:session, url: login_path, remote: true) do |f| %>
              <div><h3> <%= t('username') %> </h3> <%= f.text_field :username, :autocapitalize => "off", :required => true, :minlength => "2", size: 40, class: "form-control-dark fumee"  %></div>
              <div><h3> <%= t('password') %> </h3> <%= f.password_field :password, :required => true, :minlength => "6", size: 40, class: "form-control-dark fumee"  %></div>
              <div><%= f.submit t('go'), class: "form-button" %></div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>