config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:index, :create, :update]
  get '/room/join/:id/' => 'rooms#join'
  post '/room/leave/:id/' => 'rooms#leave'
  get '/room/share/:id/' => 'rooms#share'
  get '/room/edit/:id/' => 'rooms#edit'
  get '/join/:id' => 'rooms#directjoin'
  get '/embed/:id' => 'main#embed'

  get '/message/receive/:id' => 'chats#receive'
  post '/message/send' => 'chats#sendmsg'
  post '/room/ban' => 'rooms#ban', as: 'room_user_ban'

  patch '/user/set-name' => 'users#set_name', as: 'user_name_set'
  patch '/user/set-pass' => 'users#set_password', as: 'user_password_set'
  patch '/user/set-profile' => 'users#set_profile', as: 'user_profile_set'

  patch '/room/' => 'rooms#update'

  post '/user/hello' => 'users#hello'
  post '/user/goodbye' => 'users#goodbye'
  get '/user/:id' => 'users#show'
  delete '/user/wipe/:id' => 'users#wipe', as: 'wipe_user'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  resources :users
  root 'main#chat'

end

app/models/user.rb
class User < ActiveRecord::Base

before_validation{
  self.username = username.parameterize
#  self.email = email.downcase
}

  attr_accessor :remember_token
  mount_uploader :photo, UserPhotoUploader

  has_many :rooms
  has_many :chats
  has_many :tenancies, foreign_key: "user_id", class_name: "Tenant"

  VALID_USER_REGEX = /\A[a-zA-Z0-9-]+\z/
  validates :username, length: {minimum: 2, maximum: 15 },
                       format: { with: VALID_USER_REGEX },
                       uniqueness: { case_sensitive: false },
                       allow_blank: false;

  validates :name, length: {minimum: 2, maximum: 15 },
                   allow_blank: false;


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, allow_blank: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password validations: false

  def User.digest(string)
     cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                   BCrypt::Engine.cost
     BCrypt::Password.create(string, cost: cost)
   end

   def ban
     update_attribute(:banned_at, Time.now)
   end

   def unban
     update_attribute(:banned_at, nil)
   end


  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def set_name
    @user = current_user
    if @user && !@user.username_set
      @user.username_set = true
      @user.name = (params[:user][:username])
      if @user.update_attributes(username_params)
        #
      end
    else
      return
    end
  end

  def set_password
    @user = current_user
    if @user && @user.password.nil?
      if @user.update_attributes(password_params)
        #
      end
    end
  end

  def set_profile
    @user = current_user
    if @user
      if !@user.username_set
        @user.username_set = true
        @user.name = (params[:user][:username])
        @user.update_attributes(username_params)
        if @user.update_attributes(username_params)
          #
        end
      else
        if @user.update_attributes(profile_params)
          #
        end
      end
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def wipe
    @user = User.find_by(id: params[:id])
    if current_user && current_user.admin?
      @user.banned_at = Time.now
      @user.chats.destroy_all
      @user.rooms.destroy_all
      @user.save
    end
    render js: "alert('banned')"
  end

  def hello
    @user = current_user

    require "geoip"
    g = GeoIP.new("GeoLiteCity.dat").city(request.remote_ip)
    if !g.nil?
      @user.latitude = g.latitude
      @user.longitude = g.longitude
    end
    @user.ip_address = request.remote_ip
    
    @user.online = true
    @user.last_call = Time.now
    @user.sessions_count += 1
    @user.save
    render json: {}
  end

  def goodbye
    @user = current_user
    @user.last_call = Time.now
    @user.sessions_count -= 1

    if current_user.sessions_count <= 0
      @user.online = false
    end

    @user.save
    render json: {}
  end


  private
  def username_params
    params.require(:user).permit(:username, :photo, :name, :bio)
  end

  def password_params
    params.require(:user).permit(:password)
  end
  def profile_params
    params.require(:user).permit(:photo, :name, :bio)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show.html.erb
<div class="profile">
  <div class="form-photo">
    <% if @user.photo? %>
      <%= image_tag @user.photo.url.to_s %>
    <% else %>
      <%= image_tag "user-default.png" %>
    <% end %>
  </div>

  <h3> <%= @user.name %> (@<%= @user.username %>) </h3>

  <p> <%= @user.bio %> </p>

  <% if current_user.admin %>
    <%= link_to "Wipe", wipe_user_path, method: "delete", data: { confirm: "SURE?" },remote: true %></li>
  <% end %>

</div>

app/views/users/set_name.js.erb
<% if @user.save %>
//  $("textarea",".chat-insert").removeClass("hidden");
//  $(".form-username").remove();
//  $('#error-div').remove();
//  $("#pass-set").removeClass("hidden");
location.reload();
<% else %>
  $('#error-div').html('<%= j(render 'layouts/error', :object => @user) %>');
<% end %>

app/views/users/set_password.js.erb
<% if @user.save %>
  $("#pass-set").hide();
<% else %>
  $('#error-div').html('<%= j(render 'layouts/error', :object => @user) %>');
<% end %>

app/views/users/set_profile.js.erb
<% if @user.save %>
  location.reload();
<% else %>
  $('#error-div').html('<%= j(render 'layouts/error', :object => @user) %>');
<% end %>

app/views/users/show.js.erb
$('.window-ajax-content').html('<%= j render 'users/show' %>');
$('.side-title').html('@<%= @user.username %>');

app/views/users/update.js.erb
<% if @user.save %>
  $("textarea",".chat-insert").removeClass("hidden");
  $(".form-username").remove();
  $('#error-div').remove();

<% else %>
  $('#error-div').html('<%= j(render 'layouts/error', :object => @user) %>');
<% end %>